version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=easy  # Simple token for development
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=easy
      --NotebookApp.notebook_dir=/app
    
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: